reviewer/api/urls.py
from django.urls import include, path

from api.v1.genres.routers import router as genres_router
from api.v1.movies.routers import router as movies_router
from api.v1.persons.routers import router as persons_router
from api.v1.roles.routers import router as roles_router
from api.v1.users.routers import router as users_router

app_name = 'api'
urlpatterns = [
    path(
        '',
        include(users_router.urls),
    ),
    path(
        '',
        include(movies_router.urls),
    ),
    path(
        '',
        include(persons_router.urls),
    ),
    path(
        '',
        include(roles_router.urls),
    ),
    path(
        '',
        include(genres_router.urls),
    ),
]

reviewer/genres/urls.py
from django.urls import path

from genres.views import GenreListView, SearchView

app_name = 'genres'
urlpatterns = [
    path(
        '',
        GenreListView.as_view(),
        name='genres',
    ),
    path(
        'search/',
        SearchView.as_view(),
        name='search',
    ),
]

reviewer/movies/urls.py
from django.urls import path

from movies import views

app_name = 'movies'
urlpatterns = [
    path(
        'genre/<str:genre>/',
        views.MoviesByGenreView.as_view(),
        name='movies_by_genre',
    ),
    path(
        'detail/<int:movie_id>/',
        views.MovieDetailView.as_view(),
        name='movie_detail',
    ),
    path(
        '<int:movie_id>/actors/',
        views.MovieActorsView.as_view(),
        name='movie_actors',
    ),
    path(
        '<int:movie_id>/directors/',
        views.MovieDirectorsView.as_view(),
        name='movie_directors',
    ),
    path(
        '<int:movie_id>/producers/',
        views.MovieProducersView.as_view(),
        name='movie_producers',
    ),
    path(
        '<int:movie_id>/screenwriters/',
        views.MovieScreenwritersView.as_view(),
        name='movie_screenwriters',
    ),
    path(
        '<int:movie_id>/operators/',
        views.MovieOperatorsView.as_view(),
        name='movie_operators',
    ),
    path(
        '<int:movie_id>/composers/',
        views.MovieComposersView.as_view(),
        name='movie_composers',
    ),
    path(
        '<int:movie_id>/artists/',
        views.MovieArtistsView.as_view(),
        name='movie_artists',
    ),
    path(
        '<int:movie_id>/editors/',
        views.MovieEditorsView.as_view(),
        name='movie_editors',
    ),
    path(
        '<int:movie_id>/<str:staff_type>/search/',
        views.SearchView.as_view(),
        name='search',
    ),
    path(
        '<int:movie_id>/<str:staff_type>/search/',
        views.SearchView.as_view(),
        name='search',
    ),
]

reviewer/reviewer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin import site
from django.urls import include, path

urlpatterns = [
    path('', include('feeds.urls', namespace='feeds')),
    path('genres/', include('genres.urls', namespace='genres')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('person/', include('persons.urls', namespace='persons')),
    path('user/', include('users.urls', namespace='users')),
    path(
        'user/',
        include('django.contrib.auth.urls'),
    ),
    path(
        'api/v1/',
        include('api.urls'),
    ),
    path('admin/', site.urls),
] + (
    static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path(
            '__debug__/',
            include(debug_toolbar.urls),
        )
    ]

reviewer/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout',
    ),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='users/change_password.html'
        ),
        name='change_password',
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='users/change_password_done.html',
        ),
        name='change_password_done',
    ),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/reset_password.html',
        ),
        name='reset_password',
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/reset_password_done.html',
        ),
        name='reset_password_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/reset_password_confirm.html',
        ),
        name='reset_password_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/reset_password_complete.html',
        ),
        name='reset_password_complete',
    ),
    path(
        'signup/',
        views.SignUpView.as_view(),
        name='signup',
    ),
    path(
        'signup/done/',
        views.SignUpDoneView.as_view(),
        name='signup_done',
    ),
    path(
        'activation/done/',
        views.AccountActivationDoneView.as_view(),
        name='activation_done',
    ),
    path(
        'activation/<str:username>/',
        views.AccountActivationView.as_view(),
        name='activation',
    ),
    path(
        'profile/<str:username>/',
        views.ProfileView.as_view(),
        name='profile',
    ),
    path(
        'list/',
        views.UserListView.as_view(),
        name='userlist',
    ),
    path(
        'list/search/',
        views.SearchView.as_view(),
        name='search',
    ),
]

reviewer/templates/includes/alert.html
<svg class="alert" viewBox="-0.5 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg" style="width: 150px; display: block; margin: 10% auto;">
    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
    <g id="SVGRepo_iconCarrier"> 
        <path d="M10.8809 16.15C10.8809 16.0021 10.9101 15.8556 10.967 15.7191C11.024 15.5825 11.1073 15.4586 11.2124 15.3545C11.3175 15.2504 11.4422 15.1681 11.5792 15.1124C11.7163 15.0567 11.8629 15.0287 12.0109 15.03C12.2291 15.034 12.4413 15.1021 12.621 15.226C12.8006 15.3499 12.9399 15.5241 13.0211 15.7266C13.1024 15.9292 13.122 16.1512 13.0778 16.3649C13.0335 16.5786 12.9272 16.7745 12.7722 16.9282C12.6172 17.0818 12.4204 17.1863 12.2063 17.2287C11.9922 17.2711 11.7703 17.2494 11.5685 17.1663C11.3666 17.0833 11.1938 16.9426 11.0715 16.7618C10.9492 16.5811 10.8829 16.3683 10.8809 16.15ZM11.2408 13.42L11.1008 8.20001C11.0875 8.07453 11.1008 7.94766 11.1398 7.82764C11.1787 7.70761 11.2424 7.5971 11.3268 7.5033C11.4112 7.40949 11.5144 7.33449 11.6296 7.28314C11.7449 7.2318 11.8697 7.20526 11.9958 7.20526C12.122 7.20526 12.2468 7.2318 12.3621 7.28314C12.4773 7.33449 12.5805 7.40949 12.6649 7.5033C12.7493 7.5971 12.813 7.70761 12.8519 7.82764C12.8909 7.94766 12.9042 8.07453 12.8909 8.20001L12.7609 13.42C12.7609 13.6215 12.6809 13.8149 12.5383 13.9574C12.3958 14.0999 12.2024 14.18 12.0009 14.18C11.7993 14.18 11.606 14.0999 11.4635 13.9574C11.321 13.8149 11.2408 13.6215 11.2408 13.42Z" fill="#fecb3e"></path>
        <path d="M12 21.5C17.1086 21.5 21.25 17.3586 21.25 12.25C21.25 7.14137 17.1086 3 12 3C6.89137 3 2.75 7.14137 2.75 12.25C2.75 17.3586 6.89137 21.5 12 21.5Z" stroke="#fecb3e" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path> 
    </g>
</svg>

reviewer/templates/includes/genre_card.html
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ genre.name | title }}</h5>
        <a href="{% url 'movies:movies_by_genre' genre.name %}" class="btn btn-primary">Movies</a>
    </div>
</div>

reviewer/templates/includes/header.html
<div class="container">
    <header
        class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                <use xlink:href="#bootstrap"></use>
            </svg>
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="/" class="nav-link px-2 link-dark">Movies</a></li>
            <li><a href="{% url 'genres:genres' %}" class="nav-link px-2 link-dark">Genres</a></li>
            <li><a href="{% url 'users:userlist' %}" class="nav-link px-2 link-dark">Userlist</a></li>
            {% if user.is_staff %}
            <li><a href="{% url 'admin:index' %}" class="nav-link px-2 link-dark">Admin</a></li>
            {% endif %}
        </ul>

        <div class="col-md-3 text-end">
            {% if user.is_authenticated %}
            <a class="btn btn-primary me-2" href="{% url 'users:profile' user.username %}">Profile</a>
            <a class="btn btn-outline-primary me-2" href="{% url 'users:logout' %}">Logout</a>
            {% else %}
            <a class="btn btn-outline-primary me-2" href="{% url 'users:login' %}">Login</a>
            <a class="btn btn-primary me-2" href="{% url 'users:signup' %}">Sign Up</a>
            {% endif %}

        </div>
    </header>
</div>

reviewer/templates/includes/movie_card.html
<div class="col-sm-4">
    <div class="card">
        <img class="card-img-top" src="{{ movie.get_image_300x300 }}" alt="Image" />
        <div class="card-body">
            <h5 class="card-title">{{ movie.name }}</h5>
            <p class="card-text">{{ movie.description | truncatechars:50 }}</p>
            {% for genre in movie.genre.all %}
            <span class="badge text-bg-dark me-1">{{ genre.name }}</span>
            {% endfor %}
            <br />
            <a href="{% url 'movies:movie_detail' movie.id %}" class="btn btn-primary"
                style="margin-top: 10px;">Rates</a>
        </div>
    </div>
</div>

reviewer/templates/includes/pagination_bar.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}
        {% for p in paginator.page_range %}
        {% if page_obj.number == p %}
        <li class="page-item">
            <a class="page-link active" href="?page={{ p }}">{{ p }}</a>
        </li>
        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %} <li class="page-item">
            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
    </ul>
</nav>
{% endif %}

reviewer/templates/includes/review_card.html
<div class="card">
    <div class="card-header">
        Story: {{ review.story }} |
        Acting: {{ review.acting }} |
        Music: {{ review.music }} |
        Visual: {{ review.visual }} |
        Final: {{ review.final }} ||
        <b>Total: {{ review.total_rating }}</b>
    </div>
    <div class="card-body">
        <h5 class="card-title"><a href="{% url 'users:profile' review.user %}">{{ review.user }}</a></h5>
        <p class="card-text">{{ review.comment }}</p>
    </div>
    <div class="card-footer text-muted">{{ review.created_at }}</div>
</div>

reviewer/templates/includes/tick.html
<svg class="checkmark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52 52">
    <circle class="checkmark__circle" cx="26" cy="26" r="25" fill="none"/>
    <path class="checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8"/>
</svg>