reviewer/api/urls.py
from django.urls import include, path

from api.v1.genres.routers import router as genres_router
from api.v1.movies.routers import router as movies_router
from api.v1.persons.routers import router as persons_router
from api.v1.roles.routers import router as roles_router
from api.v1.users.routers import router as users_router

app_name = 'api'
urlpatterns = [
    path(
        '',
        include(users_router.urls),
    ),
    path(
        '',
        include(movies_router.urls),
    ),
    path(
        '',
        include(persons_router.urls),
    ),
    path(
        '',
        include(roles_router.urls),
    ),
    path(
        '',
        include(genres_router.urls),
    ),
]

reviewer/feeds/urls.py
from django.urls import path

from feeds import views

app_name = 'feeds'
urlpatterns = [
    path(
        '',
        views.NewMoviesView.as_view(),
        name='new',
    ),
    path(
        'new/',
        views.NewMoviesView.as_view(),
        name='new',
    ),
    path(
        'recently_added/',
        views.RecentlyAddedMoviesView.as_view(),
        name='recently_added',
    ),
    path(
        'best/',
        views.BestMoviesView.as_view(),
        name='best',
    ),
    path(
        'search/',
        views.SearchView.as_view(),
        name='search',
    ),
]

reviewer/reviewer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin import site
from django.urls import include, path

urlpatterns = [
    path('', include('feeds.urls', namespace='feeds')),
    path('genres/', include('genres.urls', namespace='genres')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('person/', include('persons.urls', namespace='persons')),
    path('user/', include('users.urls', namespace='users')),
    path(
        'user/',
        include('django.contrib.auth.urls'),
    ),
    path(
        'api/v1/',
        include('api.urls'),
    ),
    path('admin/', site.urls),
] + (
    static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path(
            '__debug__/',
            include(debug_toolbar.urls),
        )
    ]

reviewer/core/feeds/views.py
from django.views.generic import ListView


class FeedBaseView(ListView):
    context_object_name = 'movies'
    paginate_by = 12
    template_name = 'feeds/feed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['feed_name'] = self.__class__.feed_name
        return context

reviewer/feeds/views.py
from core.feeds.views import FeedBaseView
from core.mixins import SearchViewMixin
from movies.models import Movie


class BestMoviesView(FeedBaseView):
    feed_name = 'best'
    queryset = Movie.objects.get_best_movies()


class NewMoviesView(FeedBaseView):
    feed_name = 'new'
    queryset = Movie.objects.get_new_movies()


class RecentlyAddedMoviesView(FeedBaseView):
    feed_name = 'recently added'
    queryset = Movie.objects.get_recently_added_movies()


class SearchView(FeedBaseView, SearchViewMixin):
    feed_name = 'search'

    def get_queryset(self):
        return Movie.objects.filter(name__icontains=self.request.GET.get('q'))

reviewer/templates/feeds/feed.html
{% extends "base.html" %}

{% block title %}{{ feed_name | title }} movies {% endblock %}

{% block content %}
<div class="feed_selector" style="display: flex; flex-direction: row;">
    <h3 style="margin-left: 20px;">Feed:</h3>
    <select class="form-select form-select-sm" onchange="location = this.value"
        style="margin-left: 20px; margin-bottom: 20px; margin-right: 20px; margin-top: 3px;">
        <option selected>{{ feed_name | title }}</option>
        <option value="/new">New</option>
        <option value="/recently_added">Recently added</option>
        <option value="/best">Best</option>
    </select>
</div>

<form action="{% url 'feeds:search' %}" method="get">
    <div class="search-box" style="margin-left: 20px; margin-bottom: 10px;">
        <input type="search" name="q" placeholder="Search">
        <button type="submit" class="btn btn-primary">Search</button>
        <a href="{% url 'feeds:new' %}" class="btn btn-danger">Reset</a>
    </div>
</form>

<div class="row" style="margin-bottom: 10px; margin-left: 10px; margin-right: 10px;">
    {% for movie in movies %}
    {% include "includes/movie_card.html" %}
    {% endfor %}
</div>

{% include "includes/pagination_bar.html" %}

{% endblock %}