reviewer/api/urls.py
from django.urls import include, path

from api.v1.genres.routers import router as genres_router
from api.v1.movies.routers import router as movies_router
from api.v1.persons.routers import router as persons_router
from api.v1.roles.routers import router as roles_router
from api.v1.users.routers import router as users_router

app_name = 'api'
urlpatterns = [
    path(
        '',
        include(users_router.urls),
    ),
    path(
        '',
        include(movies_router.urls),
    ),
    path(
        '',
        include(persons_router.urls),
    ),
    path(
        '',
        include(roles_router.urls),
    ),
    path(
        '',
        include(genres_router.urls),
    ),
]

reviewer/movies/urls.py
from django.urls import path

from movies import views

app_name = 'movies'
urlpatterns = [
    path(
        'genre/<str:genre>/',
        views.MoviesByGenreView.as_view(),
        name='movies_by_genre',
    ),
    path(
        'detail/<int:movie_id>/',
        views.MovieDetailView.as_view(),
        name='movie_detail',
    ),
    path(
        '<int:movie_id>/actors/',
        views.MovieActorsView.as_view(),
        name='movie_actors',
    ),
    path(
        '<int:movie_id>/directors/',
        views.MovieDirectorsView.as_view(),
        name='movie_directors',
    ),
    path(
        '<int:movie_id>/producers/',
        views.MovieProducersView.as_view(),
        name='movie_producers',
    ),
    path(
        '<int:movie_id>/screenwriters/',
        views.MovieScreenwritersView.as_view(),
        name='movie_screenwriters',
    ),
    path(
        '<int:movie_id>/operators/',
        views.MovieOperatorsView.as_view(),
        name='movie_operators',
    ),
    path(
        '<int:movie_id>/composers/',
        views.MovieComposersView.as_view(),
        name='movie_composers',
    ),
    path(
        '<int:movie_id>/artists/',
        views.MovieArtistsView.as_view(),
        name='movie_artists',
    ),
    path(
        '<int:movie_id>/editors/',
        views.MovieEditorsView.as_view(),
        name='movie_editors',
    ),
    path(
        '<int:movie_id>/<str:staff_type>/search/',
        views.SearchView.as_view(),
        name='search',
    ),
    path(
        '<int:movie_id>/<str:staff_type>/search/',
        views.SearchView.as_view(),
        name='search',
    ),
]

reviewer/persons/urls.py
from django.urls import path

from persons.views import PersonDetailView

app_name = 'persons'
urlpatterns = [
    path(
        '<int:person_id>',
        PersonDetailView.as_view(),
        name='person_detail',
    )
]

reviewer/reviewer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin import site
from django.urls import include, path

urlpatterns = [
    path('', include('feeds.urls', namespace='feeds')),
    path('genres/', include('genres.urls', namespace='genres')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('person/', include('persons.urls', namespace='persons')),
    path('user/', include('users.urls', namespace='users')),
    path(
        'user/',
        include('django.contrib.auth.urls'),
    ),
    path(
        'api/v1/',
        include('api.urls'),
    ),
    path('admin/', site.urls),
] + (
    static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path(
            '__debug__/',
            include(debug_toolbar.urls),
        )
    ]

reviewer/movies/models.py
from django.db import models
from django.utils.safestring import mark_safe

from core.base_models import NameFormatterBaseModel
from core.mixins import ImageMixin
from genres.models import Genre
from movies.managers import MovieManager
from persons.models import Person


class Movie(NameFormatterBaseModel, ImageMixin):
    DEFAULT_IMAGE = 'images/default_movie_image.jpeg'

    name = models.CharField(
        'name', max_length=100, help_text='Maximum of 100 symbols'
    )
    formatted_name = models.CharField(
        'formatted_name',
        max_length=100,
        editable=False,
    )
    description = models.TextField(
        'description', max_length=1000, help_text='Maximum of 1000 symbols'
    )
    genre = models.ManyToManyField(
        Genre,
    )
    country = models.CharField(
        'country',
        max_length=50,
        help_text='Maximum of 50 symbols',
        null=True,
        blank=True,
    )
    actors = models.ManyToManyField(
        Person,
        related_name='actors',
        blank=True,
    )
    director = models.ManyToManyField(
        Person,
        related_name='director',
        blank=True,
    )
    producer = models.ManyToManyField(
        Person,
        related_name='producer',
        blank=True,
    )
    screenwriter = models.ManyToManyField(
        Person,
        related_name='screenwriter',
        blank=True,
    )
    operator = models.ManyToManyField(
        Person,
        related_name='operator',
        blank=True,
    )
    composer = models.ManyToManyField(
        Person,
        related_name='composer',
        blank=True,
    )
    artist = models.ManyToManyField(
        Person,
        related_name='artist',
        blank=True,
    )
    montage = models.ManyToManyField(
        Person,
        related_name='montage',
        blank=True,
    )
    budget = models.PositiveIntegerField(
        'budget',
        null=True,
        blank=True,
    )

    def get_image_path(self, filename: str) -> str:
        return f'movies/movie_{self.id}/{filename}'

    kinopoisk_link = models.CharField(
        'kinopoisk_link',
        max_length=500,
        null=True,
        blank=True,
    )
    imdb_link = models.CharField(
        'imdb_link',
        max_length=500,
        null=True,
        blank=True,
    )
    image = models.ImageField(
        'image',
        upload_to=get_image_path,
        null=True,
        default=DEFAULT_IMAGE,
    )
    created_at = models.DateField(
        'created_at',
        editable=True,
    )
    uploaded_at = models.DateField(
        'uploaded_at',
        editable=False,
        auto_now_add=True,
    )

    objects = MovieManager()

    class Meta:
        verbose_name = 'movie'
        verbose_name_plural = 'movies'

    def __str__(self):
        return self.name[:50]

    def image_tmb(self):
        if self.image:
            image_url = self.image.url
            return mark_safe(
                f'<img src="{image_url}" width="50" height="50"/>'
            )
        return 'no_photo'

    image_tmb.short_description = 'image'
    image_tmb.allow_tags = True

reviewer/api/v1/movies/views.py
from rest_framework.viewsets import ModelViewSet

from api.v1.movies.serializers import MovieSerializer
from core.api.permissions import IsAdminOrReadOnly
from movies.models import Movie


class MovieViewSet(ModelViewSet):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer
    permission_classes = (IsAdminOrReadOnly,)

reviewer/core/movies/views.py
from django.views.generic import ListView


class BaseMovieStaffView(ListView):
    context_object_name = 'persons'
    paginate_by = 10
    pk_url_kwarg = 'movie_id'
    template_name = 'movies/movie_staff.html'


class BaseMovieStaffWithModifiedContextData(BaseMovieStaffView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movie_id'] = self.kwargs[self.pk_url_kwarg]
        context['staff_type'] = self.__class__.staff_type
        return context

reviewer/movies/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView

from core.mixins import SearchViewMixin
from core.movies.views import (
    BaseMovieStaffWithModifiedContextData,
    BaseMovieStaffView,
)
from movies.models import Movie
from persons.models import Person
from rating.forms import RatingForm
from rating.models import Rating


class MovieDetailView(DetailView):
    paginate_by = 20
    pk_url_kwarg = 'movie_id'
    queryset = Movie.objects.get_for_view_details()
    template_name = 'movies/movie_detail.html'

    def get_review(self):
        try:
            review = Rating.objects.get(
                user_id=self.request.user.id,
                movie_id=self.kwargs[self.pk_url_kwarg],
            )
            return review
        except Rating.DoesNotExist:
            return None

    def get_review_form_initial_data(self, review=None) -> dict:
        if not review:
            review = Rating(
                user_id=self.request.user.id,
                movie_id=self.kwargs[self.pk_url_kwarg],
                story=Rating.ScoreData.DEFAULT,
                acting=Rating.ScoreData.DEFAULT,
                music=Rating.ScoreData.DEFAULT,
                visual=Rating.ScoreData.DEFAULT,
                final=Rating.ScoreData.DEFAULT,
            )
        initial = {
            Rating.story.field.name: review.story,
            Rating.acting.field.name: review.acting,
            Rating.music.field.name: review.music,
            Rating.visual.field.name: review.visual,
            Rating.final.field.name: review.final,
            Rating.comment.field.name: review.comment,
        }
        return initial

    def get_paginator(self):
        reviews = Rating.objects.select_related(Rating.user.field.name).filter(
            movie_id=self.kwargs[self.pk_url_kwarg]
        )
        paginator = Paginator(
            reviews,
            self.paginate_by,
        )
        page_obj = paginator.get_page(self.request.GET.get('page', 1))
        return paginator, page_obj

    def get_context_data(self, **kwargs):
        fields = [
            Rating.story.field.name,
            Rating.acting.field.name,
            Rating.music.field.name,
            Rating.visual.field.name,
            Rating.final.field.name,
        ]
        context = super().get_context_data(**kwargs)
        movie = self.object
        review = self.get_review()
        context['movie'] = movie
        context['review_exists'] = review is not None
        context['paginator'], context['page_obj'] = self.get_paginator()
        for field in fields:
            context[f'avg_{field}_rating'] = Rating.objects.get_avg(
                movie.id,
                field,
            )
        context['form'] = RatingForm(
            initial=self.get_review_form_initial_data(review=review)
        )
        return context

    def post(self, request, movie_id):
        existing_review = Rating.objects.filter(
            user_id=request.user.id,
            movie_id=self.kwargs[self.pk_url_kwarg],
        ).first()

        review_form = RatingForm(
            request.POST or None, instance=existing_review
        )
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user_id = request.user.id
            review.movie_id = movie_id
            review.save()

        return redirect(
            reverse_lazy('movies:movie_detail', kwargs=self.kwargs)
        )


class MoviesByGenreView(ListView):
    context_object_name = 'movies'
    model = Movie
    paginate_by = 12
    template_name = 'movies/movies_by_genre.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.prefetch_related('genre').filter(
            genre__name=self.kwargs.get('genre')
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre'] = self.kwargs.get('genre')
        return context


class MovieActorsView(BaseMovieStaffWithModifiedContextData):
    staff_type = 'actors'

    def get_queryset(self):
        movie = Movie.objects.filter(pk=self.kwargs[self.pk_url_kwarg]).first()
        actors = Person.objects.filter(actors__in=[movie.id])
        return actors


class MovieDirectorsView(BaseMovieStaffWithModifiedContextData):
    staff_type = 'directors'

    def get_queryset(self):
        movie = Movie.objects.filter(pk=self.kwargs[self.pk_url_kwarg]).first()
        directors = Person.objects.filter(director__in=[movie.id])
        return directors


class MovieProducersView(BaseMovieStaffWithModifiedContextData):
    staff_type = 'producers'

    def get_queryset(self):
        movie = Movie.objects.filter(pk=self.kwargs[self.pk_url_kwarg]).first()
        producers = Person.objects.filter(producer__in=[movie.id])
        return producers


class MovieScreenwritersView(BaseMovieStaffWithModifiedContextData):
    staff_type = 'screenwriters'

    def get_queryset(self):
        movie = Movie.objects.filter(pk=self.kwargs[self.pk_url_kwarg]).first()
        screenwriters = Person.objects.filter(screenwriter__in=[movie.id])
        return screenwriters


class MovieOperatorsView(BaseMovieStaffWithModifiedContextData):
    staff_type = 'operators'

    def get_queryset(self):
        movie = Movie.objects.filter(pk=self.kwargs[self.pk_url_kwarg]).first()
        operators = Person.objects.filter(operator__in=[movie.id])
        return operators


class MovieComposersView(BaseMovieStaffWithModifiedContextData):
    staff_type = 'composers'

    def get_queryset(self):
        movie = Movie.objects.filter(pk=self.kwargs[self.pk_url_kwarg]).first()
        composers = Person.objects.filter(composer__in=[movie.id])
        return composers


class MovieArtistsView(BaseMovieStaffWithModifiedContextData):
    staff_type = 'artists'

    def get_queryset(self):
        movie = Movie.objects.filter(pk=self.kwargs[self.pk_url_kwarg]).first()
        artists = Person.objects.filter(artist__in=[movie.id])
        return artists


class MovieEditorsView(BaseMovieStaffWithModifiedContextData):
    staff_type = 'editors'

    def get_queryset(self):
        movie = Movie.objects.filter(pk=self.kwargs[self.pk_url_kwarg]).first()
        editors = Person.objects.filter(montage__in=[movie.id])
        return editors


class SearchView(BaseMovieStaffView, SearchViewMixin):
    def get_queryset(self):
        staff_type = self.kwargs['staff_type']
        queryset = None
        if staff_type == 'actors':
            queryset = MovieActorsView.get_queryset(self)
        if staff_type == 'directors':
            queryset = MovieDirectorsView.get_queryset(self)
        if staff_type == 'producers':
            queryset = MovieProducersView.get_queryset(self)
        if staff_type == 'screenwriters':
            queryset = MovieScreenwritersView.get_queryset(self)
        if staff_type == 'operators':
            queryset = MovieOperatorsView.get_queryset(self)
        if staff_type == 'composers':
            queryset = MovieComposersView.get_queryset(self)
        if staff_type == 'artists':
            queryset = MovieArtistsView.get_queryset(self)
        if staff_type == 'editors':
            queryset = MovieEditorsView.get_queryset(self)
        return queryset.filter(
            Q(name__icontains=self.request.GET.get('q'))
            | Q(surname__icontains=self.request.GET.get('q'))
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q')
        context['movie_id'] = self.kwargs[self.pk_url_kwarg]
        context['staff_type'] = self.kwargs['staff_type']
        return context

reviewer/templates/movies/movie_detail.html
{% extends "base.html" %}

{% block title %}{{ movie.name | title }}{% endblock %}

{% block head %}
<style>
    table {
        border-collapse: collapse;
    }

    td,
    th {
        border: none;
    }

    td {
        padding: 10px;
    }
    .card {
        margin-left: 20px;
        margin-right: 100px;
        margin-bottom: 20px;
    }
</style>
{% endblock %}

{% block content %}
<div class="movie" style="display: flex; flex-direction: row; margin-left: 100px; margin-right: 100px;">
    <div class="images_links">
        <img src="{{ movie.get_image_300x300 }}" height="40%" />
        <div class="links">
            {% if movie.kinopoisk_link %}
            <a href="{{ movie.kinopoisk_link }}"><img src="/media/images/kinopoisk.png" width="50%"
                    style="padding-top: 10px;"></a>
            {% endif %}
            <br>
            {% if movie.imdb_link %}
            <a href="{{ movie.imdb_link }}"><img src="/media/images/imdb_informer.png" style="padding-top: 10px;"
                    width="50%"></a>
            {% endif %}
        </div>
        <br>
        <div class="description" style="width: 350px;">
            <h5>Description:</h5>
            <p>{{ movie.description }}</p>
        </div>
    </div>
    <div class="movie-info" style="margin-left: 80px;">
        <h2><b>{{ movie.name }}</b></h2>
        <h4 style="margin-top: 20px;">About movie:</h4>
        <table>
            <tr>
                <td>Year of production:</td>
                <td>{{ movie.created_at }}</td>
            </tr>
            <tr>
                <td>Country:</td>
                <td>{% if country %}{{ movie.country }}{% else %}-{% endif %}</td>
            </tr>
            <tr>
                <td>Genres:</td>
                <td>
                    {% if movie.genre.all %}
                    {% for genre in movie.genre.all %}
                    <a href="{% url 'movies:movies_by_genre' genre.name %}">
                        {% if forloop.last %}
                        {{ genre.name }} {{ genre.surname }}
                        {% else %}
                        {{ genre.name }} {{ genre.surname }},
                        {% endif %}
                    </a>
                    {% endfor %}
                    {% else %}
                    -
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Director:</td>
                <td>
                    {% if movie.director.all %}
                    {% for director in movie.director.all|slice:":3" %}
                    <a href="{% url 'persons:person_detail' director.id %}">
                        {% if forloop.last %}
                        {{ director.name }} {{ director.surname }}
                        {% else %}
                        {{ director.name }} {{ director.surname }},
                        {% endif %}
                    </a>
                    {% endfor %}
                    {% if movie.director.count > 3 %}
                    <a href="{% url 'movies:movie_director' movie.id %}">, ...</a>
                    {% endif %}
                    {% else %}
                    -
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Screenwriter:</td>
                <td>
                    {% if movie.screenwriter.all %}
                    {% for screenwriter in movie.screenwriter.all|slice:":3" %}
                    <a href="{% url 'persons:person_detail' screenwriter.id %}">
                        {% if forloop.last %}
                        {{ screenwriter.name }} {{ screenwriter.surname }}
                        {% else %}
                        {{ screenwriter.name }} {{ screenwriter.surname }},
                        {% endif %}
                    </a>
                    {% endfor %}
                    {% if movie.screenwriter.count > 3 %}
                    <a href="{% url 'movies:movie_screenwriter' movie.id %}">, ...</a>
                    {% endif %}
                    {% else %}
                    -
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Producer:</td>
                <td>
                    {% if movie.producer.all %}
                    {% for producer in movie.producer.all|slice:":3" %}
                    <a href="{% url 'persons:person_detail' producer.id %}">
                        {% if forloop.last %}
                        {{ producer.name }} {{ producer.surname }}
                        {% else %}
                        {{ producer.name }} {{ producer.surname }},
                        {% endif %}
                    </a>
                    {% endfor %}
                    {% if movie.producer.count > 3 %}
                    <a href="{% url 'movies:movie_producers' movie.id %}">, ...</a>
                    {% endif %}
                    {% else %}
                    -
                    {% endif %}
                </td>
            </tr>
            <td>Artists:</td>
                <td>
                    {% if movie.artist.all %}
                    {% for artist in movie.artist.all|slice:":3" %}
                    <a href="{% url 'persons:person_detail' artist.id %}">
                        {% if forloop.last %}
                        {{ artist.name }} {{ artist.surname }}
                        {% else %}
                        {{ artist.name }} {{ artist.surname }},
                        {% endif %}
                    </a>
                    {% endfor %}
                    {% if movie.artist.count > 3 %}
                    <a href="{% url 'movies:movie_artists' movie.id %}">, ...</a>
                    {% endif %}
                    {% else %}
                    -
                    {% endif %}
                </td>
            <tr>
                <td>Operator:</td>
                <td>
                    {% if movie.operator.all %}
                    {% for operator in movie.operator.all|slice:":3" %}
                    <a href="{% url 'persons:person_detail' operator.id %}">
                        {% if forloop.last %}
                        {{ operator.name }} {{ operator.surname }}
                        {% else %}
                        {{ operator.name }} {{ operator.surname }},
                        {% endif %}
                    </a>
                    {% endfor %}
                    {% if movie.operator.count > 3 %}
                    <a href="{% url 'movies:movie_operators' movie.id %}">, ...</a>
                    {% endif %}
                    {% else %}
                    -
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Composer:</td>
                <td>
                    {% if movie.composer.all %}
                    {% for composer in movie.composer.all|slice:":3" %}
                    <a href="{% url 'persons:person_detail' composer.id %}">
                        {% if forloop.last %}
                        {{ composer.name }} {{ composer.surname }}
                        {% else %}
                        {{ composer.name }} {{ composer.surname }},
                        {% endif %}
                    </a>
                    {% endfor %}
                    {% if movie.composer.count > 3 %}
                    <a href="{% url 'movies:movie_composers' movie.id %}">, ...</a>
                    {% endif %}
                    {% else %}
                    -
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Montage:</td>
                <td>
                    {% if movie.montage.all %}
                    {% for montage in movie.montage.all|slice:":3" %}
                    <a href="{% url 'persons:person_detail' montage.id %}">
                        {% if forloop.last %}
                        {{ montage.name }} {{ montage.surname }}
                        {% else %}
                        {{ montage.name }} {{ montage.surname }},
                        {% endif %}
                    </a>
                    {% endfor %}
                    {% if movie.montage.count > 3 %}
                    <a href="{% url 'movies:movie_editors' movie.id %}">, ...</a>
                    {% endif %}
                    {% else %}
                    -
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Budget:</td>
                <td>
                    {% if movie.budget %}
                    ${{ movie.budget }}
                    {% else %}
                    -
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>
    <div class="raiting-info">
        <h3 style="text-align: center;">Total rating:</h3>
        <h1 style="text-align: center;">{{ avg_total_rating }}</h1>
        <p style="font-size: 13px; text-align: center;">
            Story: {{ avg_story_rating }} |
            Acting: {{ avg_acting_rating }} |
            Music: {{ avg_music_rating }} |
            Visual: {{ avg_visual_rating }} |
            Final: {{ avg_final_rating }}
        </p>
        <hr>
        <h2>Your review:</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <label for="{{ field.auto_id }}">{{ field.label }}
                {% if field.value and field.name != 'comment' %}
                <span id="{{ field.auto_id }}-value"> | {{ field.value }}</span>
                {% endif %}
            </label>
            {{ field }}
            {% endfor %}
            <button class="btn btn-primary" style="margin-top: 10px;">Submit</button>
        </form>
        <span id="story-value"></span>
    </div>
</div>
<hr>
<div class="reviews">
    {% if page_obj %}
    <h2 style="margin-left: 20px;">Other reviews:</h2>
    {% for review in page_obj %}
    {% include "includes/review_card.html" %}
    {% endfor %}
    {% endif %}
</div>
{% include "includes/pagination_bar.html" %}
<script>
    document.querySelectorAll('input[type="range"]').forEach(function (input) {
        input.addEventListener('input', function () {
            var valueElementId = input.id + "-value";
            document.getElementById(valueElementId).textContent = " | " + input.value;
        });
    });
</script>
{% endblock %}

reviewer/templates/movies/movie_staff.html
{% extends "base.html" %}

{% block title %}{{ staff_type | title }}{% endblock %}

{% block content %}
<form action="{% url 'movies:search' movie_id staff_type %}" method="get">
    <div class="search-box" style="margin-left: 20px; margin-bottom: 10px;">
        <input type="search" name="q" placeholder="Search">
        <button type="submit" class="btn btn-primary">Search</button>
        {% if staff_type == 'actors' %}
        <a href="{% url 'movies:movie_actors' movie_id %}" class="btn btn-danger">Reset</a>
        {% elif staff_type == 'directors' %}
        <a href="{% url 'movies:movie_directors' movie_id %}" class="btn btn-danger">Reset</a>
        {% elif staff_type == 'producers' %}
        <a href="{% url 'movies:movie_producers' movie_id %}" class="btn btn-danger">Reset</a>
        {% elif staff_type == 'screenwriters' %}
        <a href="{% url 'movies:movie_screenwriters' movie_id %}" class="btn btn-danger">Reset</a>
        {% elif staff_type == 'operators' %}
        <a href="{% url 'movies:movie_operators' movie_id %}" class="btn btn-danger">Reset</a>
        {% elif staff_type == 'composers' %}
        <a href="{% url 'movies:movie_composers' movie_id %}" class="btn btn-danger">Reset</a>
        {% elif staff_type == 'artists' %}
        <a href="{% url 'movies:movie_artists' movie_id %}" class="btn btn-danger">Reset</a>
        {% elif staff_type == 'editors' %}
        <a href="{% url 'movies:movie_editors' movie_id %}" class="btn btn-danger">Reset</a>
        {% endif %}
    </div>
</form>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Photo</th>
            <th scope="col">Name</th>
            <th scope="col">Surname</th>
            <th scope="col">Link</th>
        </tr>
    </thead>
    <tbody>
        {% for person in persons %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><img src="{{ person.get_image_50x50 }}"/></td>
            <td>{{ person.name }}</td>
            <td>{{ person.surname }}</td>
            <td><a class="btn btn-primary" href="{% url 'persons:person_detail' person.id %}">Details</a></td>
        </tr>
        {% endfor %}
    </tbody>
{% endblock %}

reviewer/templates/movies/movies_by_genre.html
{% extends "base.html" %}

{% block title %}{{ genre | title }}{% endblock %}

{% block content %}
{% if movies %}
<h1 style="margin-left: 10px;">{{ genre | title }}</h1>
<div class="row" style="margin-bottom: 10px; margin-left: 10px; margin-right: 10px;">
    {% for movie in movies %}
    {% include "includes/movie_card.html" %}
    {% endfor %}
</div>
{% else %}
<h1>No films with this genre have been found.</h1>
{% endif %}
{% endblock %}