reviewer/api/urls.py
from django.urls import include, path

from api.v1.genres.routers import router as genres_router
from api.v1.movies.routers import router as movies_router
from api.v1.persons.routers import router as persons_router
from api.v1.roles.routers import router as roles_router
from api.v1.users.routers import router as users_router

app_name = 'api'
urlpatterns = [
    path(
        '',
        include(users_router.urls),
    ),
    path(
        '',
        include(movies_router.urls),
    ),
    path(
        '',
        include(persons_router.urls),
    ),
    path(
        '',
        include(roles_router.urls),
    ),
    path(
        '',
        include(genres_router.urls),
    ),
]

reviewer/reviewer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin import site
from django.urls import include, path

urlpatterns = [
    path('', include('feeds.urls', namespace='feeds')),
    path('genres/', include('genres.urls', namespace='genres')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('person/', include('persons.urls', namespace='persons')),
    path('user/', include('users.urls', namespace='users')),
    path(
        'user/',
        include('django.contrib.auth.urls'),
    ),
    path(
        'api/v1/',
        include('api.urls'),
    ),
    path('admin/', site.urls),
] + (
    static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path(
            '__debug__/',
            include(debug_toolbar.urls),
        )
    ]

reviewer/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout',
    ),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='users/change_password.html'
        ),
        name='change_password',
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='users/change_password_done.html',
        ),
        name='change_password_done',
    ),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/reset_password.html',
        ),
        name='reset_password',
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/reset_password_done.html',
        ),
        name='reset_password_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/reset_password_confirm.html',
        ),
        name='reset_password_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/reset_password_complete.html',
        ),
        name='reset_password_complete',
    ),
    path(
        'signup/',
        views.SignUpView.as_view(),
        name='signup',
    ),
    path(
        'signup/done/',
        views.SignUpDoneView.as_view(),
        name='signup_done',
    ),
    path(
        'activation/done/',
        views.AccountActivationDoneView.as_view(),
        name='activation_done',
    ),
    path(
        'activation/<str:username>/',
        views.AccountActivationView.as_view(),
        name='activation',
    ),
    path(
        'profile/<str:username>/',
        views.ProfileView.as_view(),
        name='profile',
    ),
    path(
        'list/',
        views.UserListView.as_view(),
        name='userlist',
    ),
    path(
        'list/search/',
        views.SearchView.as_view(),
        name='search',
    ),
]

reviewer/users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models

from core.mixins import ImageMixin
from users.managers import UserManager


class NormalizedEmailField(models.EmailField):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def get_prep_value(self, value):
        value = value.lower()
        if value:
            if '@ya.ru' in value:
                value = value.split('@')[0] + 'yandex.ru'
            if '+' in value:
                value = (
                    f'{value.split("@")[0].split("+")[0]}@'
                    f'{value.split("@")[-1]}'
                )
            username, domain = value.split('@')
            if domain == 'gmail.com':
                username = username.replace('.', '')
            elif domain == 'yandex.ru':
                username = username.replace('.', '-')
            value = f'{username}@{domain}'
        return value


class User(AbstractBaseUser, PermissionsMixin, ImageMixin):
    DEFAULT_IMAGE = 'images/default_avatar.png'

    username = models.CharField(
        'username',
        max_length=50,
        help_text='Maximum of 50 symbols',
        unique=True,
    )
    bio = models.TextField(
        'bio',
        max_length=500,
        help_text='Maximum of 500 symbols',
        default='',
        null=True,
        blank=True,
    )
    email = models.EmailField(
        'email',
        unique=True,
    )
    normalized_email = NormalizedEmailField(
        'normalized_email',
        unique=True,
    )

    def get_image_path(self, filename: str) -> str:
        return f'avatars/user_{self.id}/{filename}'

    image = models.ImageField(
        'avatar',
        upload_to=get_image_path,
        default=DEFAULT_IMAGE,
    )
    date_joined = models.DateTimeField(
        'date_joined',
        auto_now=True,
    )
    is_active = models.BooleanField(
        'active',
        default=False,
    )
    is_staff = models.BooleanField(
        'staff',
        default=False,
    )
    is_superuser = models.BooleanField(
        'superuser',
        default=False,
    )

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def natural_key(self):
        return self.username

    def save(self, *args, **kwargs):
        self.normalized_email = self.normalized_email or self.email
        super(User, self).save(*args, **kwargs)

reviewer/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from core.mixins import BootstrapFormMixin
from users.models import User


class SignUpForm(
    BootstrapFormMixin,
    UserCreationForm,
):
    class Meta:
        model = User
        fields = (
            User.username.field.name,
            User.email.field.name,
            'password1',
            'password2',
        )


class ProfileForm(BootstrapFormMixin, forms.ModelForm):
    image = forms.ImageField(
        label='Avatar',
        required=False,
        error_messages={'invalid': 'Image files only'},
        widget=forms.FileInput,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields[User.bio.field.name].required = False
        self.fields[User.email.field.name].widget.attrs['readonly'] = True

    class Meta:
        model = User
        fields = (
            User.image.field.name,
            User.username.field.name,
            User.email.field.name,
            User.bio.field.name,
        )

reviewer/api/v1/users/views.py
from rest_framework.viewsets import ModelViewSet

from api.v1.users.serializers import UserSerializer
from core.api.permissions import IsAdminOrReadOnly
from users.models import User


class UserViewSet(ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = (IsAdminOrReadOnly,)

reviewer/users/views.py
from smtplib import SMTPAuthenticationError

from django.conf import settings
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views import generic

from core.mixins import SearchViewMixin
from rating.models import Rating
from users.forms import ProfileForm, SignUpForm
from users.models import User
from users.tasks import send_email


class AccountActivationView(View):
    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, username=self.kwargs['username'])
        if timezone.now() - user.date_joined > timezone.timedelta(weeks=1):
            raise Http404
        user.is_active = True
        user.save()

        return redirect(reverse_lazy('users:activation_done'))


class AccountActivationDoneView(generic.TemplateView):
    template_name = 'users/activation_done.html'


class ProfileView(generic.UpdateView):
    context_object_name = 'profile_owner'
    form_class = ProfileForm
    paginate_by = 10
    pk_url_kwarg = 'username'
    template_name = 'users/profile.html'

    def get_paginator(self):
        user = self.get_object()
        reviews = Rating.objects.get_review_by_user_id(user.id)
        paginator = Paginator(
            reviews,
            self.paginate_by,
        )
        page_obj = paginator.get_page(self.request.GET.get('page', 1))
        return paginator, page_obj

    def get_object(self):
        return get_object_or_404(
            User.objects.get_user_profile(),
            username=self.kwargs.get(self.pk_url_kwarg),
        )

    def get_success_url(self) -> str:
        return reverse_lazy(
            'users:profile',
            kwargs={
                self.pk_url_kwarg: self.object.username,
            },
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['paginator'], context['page_obj'] = self.get_paginator()
        return context


class SignUpView(generic.CreateView):
    form_class = SignUpForm
    success_url = (
        '/'
        if settings.USERS_AUTOACTIVATE
        else reverse_lazy('users:signup_done')
    )
    template_name = 'users/signup.html'

    def send_email(self, user: User, absolute_uri: str):
        try:
            send_email.delay(user.username, user.email, absolute_uri)
        except SMTPAuthenticationError:
            user.is_active = True
            user.save()
            return redirect('/')

    def form_valid(self, form):
        user = form.save(commit=False)
        if not settings.USERS_AUTOACTIVATE:
            absolute_uri = self.request.build_absolute_uri(
                reverse_lazy('users:activation', args=[user.username])
            )
            self.send_email(user, absolute_uri)
        else:
            user.is_active = True
            user.save()
        return super().form_valid(form)


class SignUpDoneView(generic.TemplateView):
    template_name = 'users/signup_done.html'


class UserListView(generic.ListView):
    context_object_name = 'users'
    paginate_by = 30
    queryset = User.objects.all().order_by(
        User.username.field.name,
    )


class SearchView(generic.ListView, SearchViewMixin):
    context_object_name = 'users'
    paginate_by = 30

    def get_queryset(self):
        return User.objects.filter(
            username__icontains=self.request.GET.get('q')
        )

reviewer/templates/users/activation_done.html
{% extends "base.html" %}

{% load static %}

{% block title %}Done{% endblock %}

{% block head %}
<link href="{% static 'css/activation_done.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/tick_animation.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
{% include "includes/tick.html" %}
<div class="info">
    <h2 id="text">
        The account has been successfully activated.
    </h2>
    <a id="link" href="/">
        Home
    </a>
</div>
{% endblock %}

reviewer/templates/users/change_password_done.html
{% extends "base.html" %}

{% load static %}

{% block title %}Done{% endblock %}

{% block head %}
<link href="{% static 'css/activation_done.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/tick_animation.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
{% include "includes/tick.html" %}
<div class="info">
    <h2 id="text">
        Password successfully changed.
    </h2>
    <a id="link" href="/">
        Home
    </a>
</div>
{% endblock %}

reviewer/templates/users/profile.html
{% extends "base.html" %}

{% block title %}{{ profile_owner.username }}'s profile{% endblock %}

{% block head %}
<style>
.card {
    margin-right: 10px;
    margin-bottom: 20px;
}
</style>
{% endblock %}

{% block content %}
<div class="profile" style="display: flex; flex-direction: row;">
{% if user.id == profile_owner.id %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group" style="padding-left: 50px; padding-right: 100px;">
        <img src="{{ profile_owner.get_image_300x300 }}" width="300" height="300"
            style="border: 1px solid black" /><br />
        {% for field in form %}
        {{ field.label_tag }}<br />
        {{ field }}<br />
        {{ field.errors }}<br />
        {% endfor %}
    </div>
    <input type="submit" value="Submit" class="btn btn-primary" style="margin-left: 300px; margin-right: 300px;">
</form>
{% else %}
<div class="profile" style="padding-left: 50px; padding-right: 100px;">
    <img src="{{ profile_owner.get_image_300x300 }}" width="300" height="300" style="border: 1px solid black" /><br />
    <div class="render_username" style="display: flex; flex-direction: row;">
        {% if profile_owner.is_staff %}
        <h3>{{ profile_owner.username }} <span class="badge text-bg-primary me-1">STAFF</span></h3>
        {% else %}
        <h3>{{ profile_owner.username }}</h3>
        {% endif %}
    </div>
    <p>Date joined: {{ profile_owner.date_joined }}</p>
    {% if profile_owner.bio %}
    <p>Bio: {{ profile_owner.bio }}</p>
    {% endif %}
</div>
{% endif %}
<div class="reviews">
    <h2>Reviews:</h2>
    {% if page_obj %}
    {% for review in page_obj %}
    {% include "includes/review_card.html" %}
    {% endfor %}
    {% else %}
    <h5>No reviews found</h5>
    {% endif %}

    {% include "includes/pagination_bar.html" %}
</div>
</div>
{% endblock %}

reviewer/templates/users/reset_password_done.html
{% extends "base.html" %}

{% load static %}

{% block title %}Done{% endblock %}

{% block head %}
<link href="{% static 'css/password_reset_and_signup_done.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/tick_animation.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
{% include "includes/tick.html" %}
<div class="info">
    <h2 id="main_text">
        Password reset sent
    </h2>
    <p id="info_text">
        We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
    </p>
    <a id="link" href="/">
        Home
    </a>
</div>
{% endblock %}

reviewer/templates/users/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group" style="padding-left: 300px; padding-right: 300px;">
        {{ field.errors }}<br/>
        {{ field.label_tag }}<br/>
        {{ field }}<br/>
    </div>
    {% endfor %}
    <input type="submit" value="Submit" class="btn btn-primary" style="margin-left: 300px; margin-right: 300px;">
</form>
{% endblock %}

reviewer/templates/users/signup_done.html
{% extends "base.html" %}

{% load static %}

{% block title %}Done{% endblock %}

{% block head %}
<link href="{% static 'css/password_reset_and_signup_done.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
{% include "includes/alert.html" %}
<div class="info">
    <h2 id="main_text">
        Registration was successful.
    </h2>
    <p id="info_text">
        An email with a link has been sent to your email. Follow the link to confirm your account.
    </p>
    <a id="link" href="/">
        Home
    </a>
</div>
{% endblock %}

reviewer/templates/users/user_list.html
{% extends "base.html" %}

{% block title %}Userlist{% endblock %}

{% block content %}

<form action="{% url 'users:search' %}" method="get">
    <div class="search-box" style="margin-left: 20px; margin-bottom: 10px;">
        <input type="search" name="q" placeholder="Search">
        <button type="submit" class="btn btn-primary">Search</button>
        <a href="{% url 'users:userlist' %}" class="btn btn-danger">Reset</a>
    </div>
</form>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Username</th>
            <th scope="col">Link</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ user.username }}</td>
            <td><a class="btn btn-primary" href="{% url 'users:profile' user.username %}">Profile</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% include "includes/pagination_bar.html" %}

{% endblock %}